export const propertiesData = [
  {
    id: 1,
    title: "Luxury Apartment",
    address: "123 Sandton Drive, Johannesburg",
    price: 2500000,
    status: "Active",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    agent: "John Agent",
    images: 12,
    location: "Sandton, Johannesburg",
    coordinates: { lat: -26.1076, lng: 28.0567 },
    description:
      "Stunning luxury apartment with panoramic city views, modern finishes, and secure parking.",
    features: [
      "Panoramic Views",
      "Secure Parking",
      "Pool",
      "Gym",
      "24/7 Security",
    ],
    agentDetails: {
      name: "John Agent",
      phone: "+27 11 234 5678",
      email: "john@realestate.com",
    },
    listedDate: "2026-01-05",
  },
  {
    id: 2,
    title: "Modern Penthouse",
    address: "45 Sandton City, Johannesburg",
    price: 4200000,
    status: "Active",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    agent: "Sarah Smith",
    images: 15,
    location: "Sandton City",
    coordinates: { lat: -26.107, lng: 28.055 },
    description:
      "Ultra-modern penthouse with private rooftop terrace and smart home technology.",
    features: [
      "Rooftop Terrace",
      "Smart Home",
      "Wine Cellar",
      "Home Theater",
      "3 Parking",
    ],
    agentDetails: {
      name: "Sarah Smith",
      phone: "+27 11 234 5679",
      email: "sarah@realestate.com",
    },
    listedDate: "2026-01-03",
  },
  {
    id: 3,
    title: "Executive Villa",
    address: "78 Morningside, Sandton",
    price: 18500000,
    status: "Active",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4500,
    agent: "Mike Brown",
    images: 20,
    location: "Morningside, Sandton",
    coordinates: { lat: -26.108, lng: 28.0575 },
    description:
      "Luxurious executive villa with landscaped gardens, staff quarters, and pool house.",
    features: [
      "Staff Quarters",
      "Pool House",
      "Wine Cellar",
      "Home Gym",
      "5 Car Garage",
    ],
    agentDetails: {
      name: "Mike Brown",
      phone: "+27 11 234 5680",
      email: "mike@realestate.com",
    },
    listedDate: "2025-12-20",
  },
  {
    id: 4,
    title: "City View Loft",
    address: "22 Sandton CBD",
    price: 1800000,
    status: "Active",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    agent: "Emma Wilson",
    images: 10,
    location: "Sandton CBD",
    coordinates: { lat: -26.1065, lng: 28.058 },
    description:
      "Modern open-plan loft with exposed brick walls and industrial chic design.",
    features: [
      "Open Plan",
      "Exposed Brick",
      "High Ceilings",
      "City Views",
      "Secure",
    ],
    agentDetails: {
      name: "Emma Wilson",
      phone: "+27 11 234 5681",
      email: "emma@realestate.com",
    },
    listedDate: "2026-01-07",
  },
  {
    id: 5,
    title: "Garden Townhouse",
    address: "15 Bryanston, Sandton",
    price: 9500000,
    status: "Under Offer",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3200,
    agent: "David Lee",
    images: 14,
    location: "Bryanston, Sandton",
    coordinates: { lat: -26.109, lng: 28.054 },
    description:
      "Spacious family townhouse with private garden and solar heating system.",
    features: [
      "Solar Heating",
      "Private Garden",
      "Braai Area",
      "Study",
      "Double Garage",
    ],
    agentDetails: {
      name: "David Lee",
      phone: "+27 11 234 5682",
      email: "david@realestate.com",
    },
    listedDate: "2026-01-02",
  },
  {
    id: 6,
    title: "Waterfront Apartment",
    address: "89 Atlantic Beach",
    price: 3200000,
    status: "Active",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2100,
    agent: "Lisa Chen",
    images: 18,
    location: "Atlantic Beach, Cape Town",
    coordinates: { lat: -33.908, lng: 18.415 },
    description:
      "Beautiful waterfront apartment with sea views and direct beach access.",
    features: [
      "Ocean Views",
      "Beach Access",
      "Balcony",
      "Secure Parking",
      "Pool",
    ],
    agentDetails: {
      name: "Lisa Chen",
      phone: "+27 21 456 7890",
      email: "lisa@realestate.com",
    },
    listedDate: "2026-01-10",
  },
  {
    id: 7,
    title: "Modern Family Home",
    address: "34 Parktown, Johannesburg",
    price: 8500000,
    status: "Active",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3800,
    agent: "James Wilson",
    images: 16,
    location: "Parktown, Johannesburg",
    coordinates: { lat: -26.189, lng: 28.043 },
    description:
      "Contemporary family home with open-plan living and landscaped garden.",
    features: [
      "Open Plan",
      "Study",
      "Entertainment Area",
      "Garden",
      "Double Garage",
    ],
    agentDetails: {
      name: "James Wilson",
      phone: "+27 11 345 6789",
      email: "james@realestate.com",
    },
    listedDate: "2026-01-08",
  },
  {
    id: 8,
    title: "Investment Property",
    address: "67 Rosebank",
    price: 1500000,
    status: "Rented",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    agent: "Sophia Martinez",
    images: 8,
    location: "Rosebank, Johannesburg",
    coordinates: { lat: -26.142, lng: 28.042 },
    description:
      "Great investment property currently rented with stable tenant.",
    features: ["Investment", "Rented", "Secure", "Parking", "Near Transport"],
    agentDetails: {
      name: "Sophia Martinez",
      phone: "+27 11 567 8901",
      email: "sophia@realestate.com",
    },
    listedDate: "2025-11-15",
  },
  {
    id: 9,
    title: "Luxury Penthouse Suite",
    address: "101 Sandton Towers",
    price: 12500000,
    status: "Active",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 5200,
    agent: "Robert Johnson",
    images: 22,
    location: "Sandton Towers",
    coordinates: { lat: -26.105, lng: 28.053 },
    description:
      "Ultra-luxurious penthouse with 360-degree city views and premium finishes.",
    features: [
      "360° Views",
      "Private Elevator",
      "Wine Cellar",
      "Home Cinema",
      "4 Parking",
    ],
    agentDetails: {
      name: "Robert Johnson",
      phone: "+27 11 678 9012",
      email: "robert@realestate.com",
    },
    listedDate: "2026-01-12",
  },
  {
    id: 10,
    title: "Cozy Studio Apartment",
    address: "28 Melville, Johannesburg",
    price: 850000,
    status: "Active",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    agent: "Amanda Taylor",
    images: 6,
    location: "Melville, Johannesburg",
    coordinates: { lat: -26.169, lng: 28.011 },
    description: "Perfect starter home or investment in trendy Melville area.",
    features: [
      "Modern",
      "Secure",
      "Pet Friendly",
      "Near Restaurants",
      "Parking",
    ],
    agentDetails: {
      name: "Amanda Taylor",
      phone: "+27 11 789 0123",
      email: "amanda@realestate.com",
    },
    listedDate: "2026-01-09",
  },
  {
    id: 11,
    title: "Commercial Office Space",
    address: "200 Sandton Business District",
    price: 18500000,
    status: "Active",
    bedrooms: 0,
    bathrooms: 4,
    sqft: 8500,
    agent: "Michael Brown",
    images: 15,
    location: "Sandton Business District",
    coordinates: { lat: -26.106, lng: 28.052 },
    description:
      "Prime commercial office space in Sandton's business district.",
    features: ["Commercial", "A-Grade", "Parking", "Security", "Fiber Ready"],
    agentDetails: {
      name: "Michael Brown",
      phone: "+27 11 890 1234",
      email: "michael@realestate.com",
    },
    listedDate: "2026-01-14",
  },
  {
    id: 12,
    title: "Vacation Home",
    address: "12 Clifton, Cape Town",
    price: 28500000,
    status: "Active",
    bedrooms: 6,
    bathrooms: 5,
    sqft: 6800,
    agent: "Jennifer Davis",
    images: 25,
    location: "Clifton, Cape Town",
    coordinates: { lat: -33.938, lng: 18.378 },
    description: "Luxury vacation home with stunning Atlantic Ocean views.",
    features: [
      "Ocean Front",
      "Pool",
      "Private Beach",
      "Staff Quarters",
      "Wine Cellar",
    ],
    agentDetails: {
      name: "Jennifer Davis",
      phone: "+27 21 234 5678",
      email: "jennifer@realestate.com",
    },
    listedDate: "2026-01-06",
  },
];
